language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

script:
  - chmod 755 ./node_modules/.bin/*
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lijxug"
  - git config user.email "lijxug@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
